# HW6 Q5
### EECS 16A: Designing Information Devices and Systems I, Fall 2016

# Circuit solver
In this question we will write a program that solves circuits methodically, able to include both voltage and current souces.

In [1]:
import numpy as np
from numpy import linalg
from __future__ import print_function

(i) Write the incidence matrix F for the graph, considering $v_1$ and $v_4$ as a combined "supernode".

In [2]:
F = np.array([[-1,0,1],[1,-1,0],[0,-1,1],[1,0,-1],[0,1,-1]]) # circuit edge-node incidence matrix
print('\nF:\n',F)


F:
 [[-1  0  1]
 [ 1 -1  0]
 [ 0 -1  1]
 [ 1  0 -1]
 [ 0  1 -1]]


(ii) Specify the resistance matrix R and the vector of voltage sources $\vec{b}$.

In [3]:
R1 = 100000
R2 = 200
R3 = 100
R4 = 100000
R5 = 100
Rvec = np.array([R1,R2,R3,R4,R5])
R = np.eye(5)*Rvec # circuit resistance matrix

b = np.array([[10,0,10,0,0]]).T

# For convenience, we will define the conductance matrix G as the inverse of R.
G = np.linalg.inv(R)

print('\nR:\n',R)
print('\nb:\n',b)


R:
 [[ 100000.       0.       0.       0.       0.]
 [      0.     200.       0.       0.       0.]
 [      0.       0.     100.       0.       0.]
 [      0.       0.       0.  100000.       0.]
 [      0.       0.       0.       0.     100.]]

b:
 [[10]
 [ 0]
 [10]
 [ 0]
 [ 0]]


(iii) Write down the vector f so that KCL is satisfied as: $F^T i + f = 0$

In [4]:
f = np.array([[0],[0],[0],[0]])
print('\nf:\n', f)


f:
 [[0]
 [0]
 [0]
 [0]]


(iii) What is the rank of F? Does it have a null space? If so, what is it?

The rank of F is 2, and it has a null space of dimension 1 which is span$\{\begin{bmatrix}1 \\ 1 \\ 1\end{bmatrix}\}$

In [5]:
# any code you write to help you answer above



(iv) Setting a potential in v to 0 corresponds to deleting a column of F. Let $v_4 = 0$, and write down our new "grounded" matrix F: F_grounded

In [6]:
F_grounded = F[:, :2]
print('\nF_grounded:\n', F_grounded)


F_grounded:
 [[-1  0]
 [ 1 -1]
 [ 0 -1]
 [ 1  0]
 [ 0  1]]


(v) Implement your algebraic solution to compute v in terms of F, G, $\vec{f}$, and $\vec{b}$. You may also have to slice $\vec{f}$ and $\vec{b}$.

In [1]:
A = np.dot(np.dot(np.transpose(F_grounded), G), F_grounded)
print('\nA:\n', A)

B = np.linalg.inv(A)
print('\nB:\n', B)

v = - B.dot(f[1:3] + F_grounded.T.dot(G.dot(b)))
print('\nv:\n', v)

NameError: name 'np' is not defined

(vi) Compute $\vec{i}$ with your solution of $\vec{v}$.

In [8]:
i = G.dot(F_grounded.dot(v) + b)

print('\ni:\n', i)


i:
 [[ -9.89552239e-05]
 [  9.96020896e-02]
 [  1.00248955e-01]
 [  1.98955224e-04]
 [ -2.48955224e-04]]
